import os

import API


def conversion_thermal(antares_dataset, atlas_dataset, p):
    # The following file contains various thermal parameters defined per technology or/and specific instances
    thermic_properties = [
        "MinimumStablePowerDuration",
        "StartupDelayProbability",
        "StartupDuration",
        "ShutdownDuration",
        "MaximumGradient",
        "Strategy",
        "SetupDelay",
    ]
    antares_technology = ["Nuclear", "Lignite", "Oil", "Other", "Hard_Coal", "Mixed_fuel", "Gas"]
    thermic_parameter = {}
    thermic_index = {}

    if os.path.isfile(p.thermic_config_file):
        f = open(p.thermic_config_file)
        lines_list = f.readlines()
        f.close()
        interval_length = len(lines_list)

        for row_index, line in enumerate(lines_list[0:interval_length]):
            if row_index == 0:
                headers = line.split(";")
                for i in range(len(headers)):
                    if headers[i].strip() in thermic_properties:
                        thermic_parameter[headers[i].strip()] = {}
                        thermic_index[headers[i].strip()] = i
            if row_index > 0:
                splitted_line = line.split(";")
                if not len(splitted_line) == len(headers):
                    msg = f"The number of columns is invalid on line {str(row_index + 1)}. Please modify the ThermicParameters file before proceeding again."
                    raise ValueError(msg)
                if splitted_line[0] in antares_technology or antares_dataset.ThermalTechnology.CheckInstanceExists(
                    splitted_line[0]
                ):
                    for key, value in thermic_index.items():
                        if key == "Strategy":
                            thermic_parameter[key][splitted_line[0]] = splitted_line[value].strip()
                        else:
                            thermic_parameter[key][splitted_line[0]] = float(splitted_line[value])
                else:
                    msg = (
                        f"{splitted_line[0]} on line {str(row_index + 1)} in the ThermicParameters file is not corresponding to a valid Antares technology nor \
                        to an existing instance. It will therefore be ignored."
                    )
                    API.IO.Trace.Log(msg, API.IO.LogTypeWarn)

    if p.verbose:
        for name in thermic_properties:
            if name in thermic_parameter.keys():
                msg = f"{name} values are: {thermic_parameter[name]}"
                API.IO.Trace.Log(msg, API.IO.LogTypeInfo)

    # Construct the Thermic objects based on the ThermalTechnology of the input marker
    # Select only thermal equipments belonging to areas defined in the parameter MarketAreas and with a type not excluded
    for antares_thermal in antares_dataset.ThermalTechnology.GetAllInstances():
        # The marker generated by the parser module defines the names of the thermal technologies as a
        # combination of the node name and the name of the cluster separated by _
        mkt_name = antares_thermal.Name.split("_")[0]
        # Apply the converter only on thermal clusters non excluded and belonging to the areas defined in market_areas_list
        if mkt_name in p.market_areas_list and antares_thermal.Group not in p.excluded_thermic_groups:
            try:
                sc = antares_thermal.ThermalSelectedScenario[p.scenario - 1]
                maximum_power_ts = antares_thermal.Disponibility[sc - 1]
            except:
                maximum_power_ts = (
                    antares_thermal.NominalCapacity
                    * antares_thermal.UnitCount
                    * antares_thermal.CapacityModulation
                    * (1.0 - antares_thermal.FORate)
                    * (1.0 - antares_thermal.PORate)
                )

            if (
                maximum_power_ts.Abs().Max() == 0.0
                or antares_thermal.NominalCapacity * antares_thermal.UnitCount == 0.0
            ):
                continue

            equipment = atlas_dataset.Equipment.Thermic.CreateInstance(antares_thermal.Name)

            # FC: Following property previously set to True, corrected to False because
            # Thermic equipments have no value in MinimumDailyEnergy and MaximumDailyEnergy as of February 2022
            equipment.HasDailyEnergyConstraint = False

            node = atlas_dataset.Network.Node.GetInstanceByName(mkt_name)
            equipment.Node = node

            if p.consumption_production_separation:
                equipment.Portfolio = atlas_dataset.MarketAgent.Portfolio.GetInstanceByName(f"generator_{mkt_name}")
            else:
                equipment.Portfolio = atlas_dataset.MarketAgent.Portfolio.GetInstanceByName(f"portfolio_{mkt_name}")

            equipment.MaximumPower = maximum_power_ts

            equipment.MinimumPower = API.TimeSeries.NewTimeSeries(
                "MinPower",
                API.TimeSeries.Constant,
                p.start_date.ToString(),
                "1Y",
                2,
                float(antares_thermal.MinStablePower),
                "MW",
            )

            equipment.InstalledCapacity = antares_thermal.NominalCapacity * antares_thermal.UnitCount

            # WARNING : note that if the parameter use_multi_energy is set to True, this VariableCost will be overwrited for units using CH4 in the multi_energy.py file
            if antares_thermal.MarketBidCost > 0:
                equipment.VariableCost = float(antares_thermal.MarketBidCost) * antares_thermal.MarketBidModulation
            else:
                equipment.VariableCost = float(antares_thermal.MarginalCost) * antares_thermal.MarginalCostModulation

            equipment.StartupCost = API.TimeSeries.NewTimeSeries(
                "StartupCost",
                API.TimeSeries.Constant,
                p.start_date.ToString(),
                "1Y",
                2,
                float(antares_thermal.StartupCost),
                "MW",
            )

            # the unit of CO2 emissions is the same in Antares and Atlas
            if antares_thermal.CO2 != 0.0:
                equipment.CO2EmissionFactor = float(antares_thermal.CO2)
            else:
                for techno in ["Nuclear", "Lignite", "Oil", "Gas", "Coal", "CCGT", "OCGT"]:
                    if techno in equipment.Name:
                        equipment.CO2EmissionFactor = p.co2_emission_factors[techno]
                        break
                    msg = (
                        f"Thermal technology for equipment {equipment.Name} did not match hardcoded groups. CO2EmissionFactor is set \
                        to default value for this unit"
                    )
                    API.IO.Trace.Log(msg, API.IO.LogTypeWarn)

            if antares_thermal.FODuration.IsEmpty:
                equipment.OutageMeanDuration = 0
            else:
                equipment.OutageMeanDuration = antares_thermal.FODuration.Average() * 24

            if antares_thermal.PODuration.IsEmpty:
                equipment.ScheduledShutdownMeanDuration = 0
            else:
                equipment.ScheduledShutdownMeanDuration = antares_thermal.PODuration.Average() * 24

            if antares_thermal.FORate.IsEmpty:
                equipment.OutageProbability = 0
            else:
                equipment.OutageProbability = antares_thermal.FORate.Average()

            if antares_thermal.PORate.IsEmpty:
                equipment.ScheduledShutdownProbability = 0
            else:
                equipment.ScheduledShutdownProbability = antares_thermal.PORate.Average()

            equipment.MinimumTimeOff = antares_thermal.MinDownTime
            equipment.MinimumTimeOn = antares_thermal.MinUpTime

            # Store properties indicated in the ThermicParameters csv
            for name in thermic_properties:
                if name == "MaximumGradient":
                    if name in thermic_parameter.keys():
                        if antares_thermal.Name in thermic_parameter[name].keys():
                            equipment.SetPropertyByName(
                                name, thermic_parameter[name][antares_thermal.Name] * antares_thermal.UnitCount
                            )
                        elif antares_thermal.Group in thermic_parameter[name].keys():
                            equipment.SetPropertyByName(
                                name, thermic_parameter[name][antares_thermal.Group] * antares_thermal.UnitCount
                            )
                else:
                    if name in thermic_parameter.keys():
                        if antares_thermal.Name in thermic_parameter[name].keys():
                            equipment.SetPropertyByName(name, thermic_parameter[name][antares_thermal.Name])
                        elif antares_thermal.Group in thermic_parameter[name].keys():
                            equipment.SetPropertyByName(name, thermic_parameter[name][antares_thermal.Group])

    return thermic_parameter, thermic_properties
