"""Copyright (c) 2025, RTE (www.rte-france.com)

SPDX-License-Identifier: MPL-2.0
This file is part of the ATLAS project.

Non-regression validation for the ThermalDispatch refactoring.

Compares LP files generated by the *current* code (using ThermalDispatch)
against the *legacy* reference LP files (generated before the refactoring).
The two sets use different variable-naming and constraint-naming conventions,
so a hybrid approach is used:

  - Variables / objective : compared by normalized names (old → new convention)
  - Constraints           : compared by structural signature (name-agnostic)
    Each constraint is represented as (sorted[(norm_var, coeff)...], lb, ub).
    Mismatches report the full coefficient row so you can trace back to the code.

Once this suite passes for all 8 combinations the reference LP files can be
regenerated with the new naming and this file can be removed.

Legacy naming  →  Current naming
─────────────────────────────────────────────────────────────────
OFF_equip_{u}_at_{t}                         off_{u}_{t}
ON_UP_equip_{u}_at_{t}                       on_up_{u}_{t}
ON_DOWN_equip_{u}_at_{t}                     on_down_{u}_{t}
turned_on_equip_{u}_at_{t}                   t_on_{u}_{t}
turned_off_equip_{u}_at_{t}                  t_off_{u}_{t}
power_equip_{u}_at_{t}                       {u}_power_level_{t}   ← unit first
reservesUp_equip_{u}_at_{t}                  reserves_up_{u}_{t}
reservesDown_equip_{u}_at_{t}                reserves_down_{u}_{t}
automatedReservesUp_equip_{u}_at_{t}         automated_reserves_up_{u}_{t}
automatedReservesDown_equip_{u}_at_{t}       automated_reserves_down_{u}_{t}
relaxedReserves_equip_{u}_at_{t}             relaxed_reserves_{u}_{t}
unprovidedReservesUp_equip_{u}_at_{t}        unprovided_reserves_up_{u}_{t}
unprovidedReservesDown_equip_{u}_at_{t}      unprovided_reserves_down_{u}_{t}
contractedDifferenceUp_equip_{u}_at_{t}      contracted_difference_up_{u}_{t}
contractedDifferenceDown_equip_{u}_at_{t}    contracted_difference_down_{u}_{t}
automatedContractedDifferenceUp_equip_{u}_at_{t}   automated_contracted_difference_up_{u}_{t}
automatedContractedDifferenceDown_equip_{u}_at_{t} automated_contracted_difference_down_{u}_{t}
"""

import re
import tempfile
from collections import Counter
from pathlib import Path

import pytest

from atlas.io_utils.atlas_dataset import AtlasDataset
from atlas.modules.day_ahead_orders.module import DayAheadOrdersModule
from atlas.solver.solver_helper import SolverHelper

THERMAL_COMBINATIONS_DIR = Path("tests/dataset/thermals-dataset")
LEGACY_LP_DIR = Path(__file__).parent / "lp_files" / "thermal"

# Timestamp pattern at the end of legacy variable names: YYYY_MM_DD_HH_MM_SS_TZ_TZ
_TIMESTAMP_RE = re.compile(r"(\d{4}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2})$")

# ── Pattern A: {ROLE}_equip_{unit}_at_{time} ──────────────────────────────────
# Maps legacy role prefix → new role prefix.
# "power" and "down_to_stop" are handled separately.
_EQUIP_PREFIX_MAP: dict[str, str] = {
    "OFF": "off",
    "ON_UP": "on_up",
    "ON_DOWN": "on_down",
    "ON_FLAT": "on_flat",
    "START": "on_start",
    "STOP": "stop",
    "turned_on": "t_on",
    "turned_off": "t_off",
    "reservesUp": "reserves_up",
    "reservesDown": "reserves_down",
    "automatedReservesUp": "automated_reserves_up",
    "automatedReservesDown": "automated_reserves_down",
    "relaxedReserves": "relaxed_reserves",
    "unprovidedReservesUp": "unprovided_reserves_up",
    "unprovidedReservesDown": "unprovided_reserves_down",
    "contractedDifferenceUp": "contracted_difference_up",
    "contractedDifferenceDown": "contracted_difference_down",
    "automatedContractedDifferenceUp": "automated_contracted_difference_up",
    "automatedContractedDifferenceDown": "automated_contracted_difference_down",
}

# ── Pattern B: {role}_at_{time}  (no unit embedded, time before unit) ─────────
# These gradient/state variables did not embed the unit name in the legacy code.
# The new ThermalDispatch appends the unit: {new_role}_{time}_{unit}.
_AT_PREFIX_MAP: dict[str, str] = {
    "UP_grad": "up_grad",
    "DOWN_grad": "down_grad",
    "aux_up_grad": "aux_up_grad",
    "aux_down_grad": "aux_down_grad",
    "entered_up": "entered_up",
    "entered_down": "entered_down",
    "stable": "stable",
    "flat_down_stop": "flat_down_stop",
    # DD variants: the legacy used either "DD_at" or "DD" depending on combination
    "DD_at": "dd_grad",
    "DD": "dd_grad",
}

# Gradient variable prefixes whose bounds differ between legacy and current:
# legacy used global max_power over the horizon; ThermalDispatch uses per-timestep max_power.
# The new bounds are strictly tighter (valid relaxation) — excluded from bounds comparison.
_GRADIENT_VAR_PREFIXES: frozenset[str] = frozenset(
    {"up_grad", "down_grad", "aux_up_grad", "aux_down_grad", "dd_grad", "down_to_stop_grad"}
)


def _normalize_legacy_name(name: str, unit: str) -> str:
    """
    Translate a single legacy DA variable name to its current ThermalDispatch equivalent.

    Three naming patterns exist in the legacy LP files:

    - Pattern A: ``{ROLE}_equip_{unit}_at_{time}`` — standard DA variables
    - Pattern C: ``{role}_at_{time}_equip_{unit}`` — gradient/state variables (time first)
    - Pattern C': ``{role}_{time}_equip_{unit}``  — DD variant without ``_at_``

    :param name: Legacy variable name.
    :param unit: The thermal unit name (used to validate the unit embedded in the name).
    :return: Normalized name, or *name* unchanged if no mapping is found.
    """
    if "_equip_" not in name:
        return name

    role, rest = name.split("_equip_", maxsplit=1)
    at_idx = rest.rfind("_at_")

    if at_idx != -1:
        # ── Pattern A: {ROLE}_equip_{unit}_at_{time} ──────────────────────────
        eq_unit = rest[:at_idx]
        timestamp = rest[at_idx + 4:]
        if not _TIMESTAMP_RE.match(timestamp):
            return name

        if role == "power":
            return f"{eq_unit}_power_level_{timestamp}"
        if role == "down_to_stop":
            return f"down_to_stop_grad_{timestamp}_{eq_unit}"

        new_role = _EQUIP_PREFIX_MAP.get(role)
        if new_role is None:
            return name
        return f"{new_role}_{eq_unit}_{timestamp}"

    # ── Patterns C / C': gradient vars — time is embedded in "role" part ──────
    # rest is just the unit name here (no "_at_" in it).
    eq_unit = rest  # unit embedded after _equip_

    # Pattern C: {role}_at_{time}_equip_{unit}
    role_at_idx = role.rfind("_at_")
    if role_at_idx != -1:
        role_candidate = role[:role_at_idx]
        timestamp = role[role_at_idx + 4:]
        if _TIMESTAMP_RE.match(timestamp):
            new_role = _AT_PREFIX_MAP.get(role_candidate)
            if new_role is not None:
                return f"{new_role}_{timestamp}_{eq_unit}"

    # Pattern C': {role}_{time}_equip_{unit}  (e.g. DD_{time}_equip_{unit})
    parts = role.split("_", maxsplit=1)
    if len(parts) == 2 and parts[0] in _AT_PREFIX_MAP and _TIMESTAMP_RE.match(parts[1]):
        return f"{_AT_PREFIX_MAP[parts[0]]}_{parts[1]}_{eq_unit}"

    return name


def _extract_unit_name(lp_data: dict) -> str:
    """
    Derive the thermal unit name from an LP data dict.

    The unit name is embedded in variables such as ``off_{unit}_{timestamp}``.
    We locate the first ``off_`` variable and strip the well-known timestamp suffix.
    Falls back to an empty string if the pattern is not found.
    """
    timestamp_re = re.compile(r"_\d{4}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}_\d{2}$")
    for var_name in lp_data.get("variables", {}):
        if var_name.startswith("off_"):
            return timestamp_re.sub("", var_name[len("off_"):])
    return ""


def _constraint_signature(constraint: dict, unit: str) -> tuple:
    """
    Build a hashable, name-agnostic signature for a single constraint.

    The signature is ``(sorted_var_rows, lb, ub)`` where each var row is
    ``(normalized_variable_name, coefficient)``.  Sorting makes it
    order-independent while keeping variable names for debuggability.
    """
    vars_items = tuple(
        sorted(
            (_normalize_legacy_name(var, unit), round(coeff, 8))
            for var, coeff in constraint.get("vars", {}).items()
        )
    )
    lb = constraint.get("lb")
    ub = constraint.get("ub")
    return (vars_items, lb, ub)


def _constraint_signatures(lp_data: dict, unit: str) -> Counter:
    return Counter(
        sig
        for c in lp_data["constraints"].values()
        if (sig := _constraint_signature(c, unit))[0]  # skip empty rows (LP parser artifacts)
    )


def _normalize_lp_named(lp_data: dict, unit: str) -> dict:
    """Return a copy with variable names translated (objectives + variable bounds only)."""

    def rename(mapping: dict) -> dict:
        return {_normalize_legacy_name(k, unit): v for k, v in mapping.items()}

    return {
        "objectives": rename(lp_data.get("objectives", {})),
        "variables": rename(lp_data.get("variables", {})),
        "constraints": lp_data.get("constraints", {}),
        "binaries": [_normalize_legacy_name(b, unit) for b in lp_data.get("binaries", [])],
    }


@pytest.fixture
def base_parameters_dict():
    return {
        "temporal": {
            "start_date": "2028-09-27 00:00:00",
            "execution_date": "2028-09-26 12:00:00",
            "end_date": "2028-09-28 00:00:00",
            "timestep": "PT1H",
        },
        "solver": {
            "solver_name": "SCIP",
            "export_lp": True,
            "use_presolve": True,
            "duality_gap": 0.0001,
            "timeout": "PT120S",
        },
        "proportional_reserves_penalty": True,
        "automated_unprocured_reserves_penalty": 10000,
        "battery_smoothing_factor": 0.1,
        "ev_energy_coef": 1.5,
        "ev_smoothing_factor": 0.1,
        "epsilon": 0.001,
        "hydraulic_minimal_fragment_size": 100,
        "load_price": 3000,
        "manual_unprocured_reserves_penalty": 100,
        "phs_smoothing_factor": 0.2,
        "battery_nb_fragments": 3,
        "ev_nb_fragments": 3,
        "phs_nb_fragments": 3,
        "price_forecasts_types": ["Medium"],
    }


@pytest.fixture(params=[1, 2, 3, 4, 5, 6, 7, 8])
def thermal_combination(request):
    num = request.param
    combination_dir = THERMAL_COMBINATIONS_DIR / f"thermal-combination-{num}"
    legacy_lp = LEGACY_LP_DIR / f"dao-combination-{num}.lp"

    if not combination_dir.exists():
        pytest.skip(f"Dataset not found: {combination_dir}")
    if not legacy_lp.exists():
        pytest.skip(f"Legacy LP not found: {legacy_lp}")

    return num, combination_dir, legacy_lp


def _generate_current_lp(combination_dir: Path, params: dict) -> dict:
    with tempfile.TemporaryDirectory() as tmpdir:
        params = params.copy()
        params["output"] = {"output_dir": tmpdir}
        DayAheadOrdersModule().run(AtlasDataset.from_directory(combination_dir), params)
        lp_files = list((Path(tmpdir) / "lp_export").glob("*.lp"))
        assert lp_files, f"No LP generated for {combination_dir.name}"
        return SolverHelper.read_lp_ortools(str(lp_files[0]))


class TestThermalNonRegression:
    """
    Validates that the ThermalDispatch refactoring did not change the
    mathematical content of the LP — only the naming conventions.
    """

    def test_variables_and_objective_match(self, thermal_combination, base_parameters_dict):
        """Variable bounds and objective coefficients are identical after name normalization.

        Gradient variables (up_grad, down_grad, aux_up_grad, aux_down_grad, dd_grad,
        down_to_stop_grad) are excluded from the bounds comparison: the legacy code
        computed bounds from the global maximum power over the horizon while ThermalDispatch
        uses per-timestep maximum_power.  The new bounds are strictly tighter, which is a
        valid relaxation that does not change the optimal solution.
        """
        num, combination_dir, legacy_lp = thermal_combination

        current = _generate_current_lp(combination_dir, base_parameters_dict)
        legacy_raw = SolverHelper.read_lp_ortools(str(legacy_lp))
        unit = _extract_unit_name(current)
        legacy = _normalize_lp_named(legacy_raw, unit)

        def _drop_gradient_vars(lp: dict) -> dict:
            return {
                **lp,
                "variables": {
                    k: v
                    for k, v in lp["variables"].items()
                    if not any(k.startswith(pfx + "_") for pfx in _GRADIENT_VAR_PREFIXES)
                },
            }

        legacy_cmp = _drop_gradient_vars(legacy)
        current_cmp = _drop_gradient_vars(current)

        with tempfile.TemporaryDirectory() as compare_dir:
            result = SolverHelper.compare_lp_problems(
                legacy_cmp,
                current_cmp,
                output_dir=compare_dir,
                pb1_name="Legacy (normalized)",
                pb2_name="Current",
                tolerance=1,
                normalize_names=False,
                keep_identical=False,
            )

        for category in ("objectives", "variables"):
            assert result[category]["identical_pct"] == 100.0, (
                f"[combination-{num}] {category}: {result[category]['identical_pct']:.1f}% identical — "
                f"only_legacy={result[category]['only_legacy']}, "
                f"only_current={result[category]['only_atlas']}, "
                f"modified={result[category]['modified']}"
            )

    def test_constraints_structurally_match(self, thermal_combination, base_parameters_dict):
        """
        Constraints are identical as mathematical rows (name-agnostic comparison).

        Each constraint is fingerprinted as (sorted[(normalized_var, coeff)...], lb, ub).
        If this test fails, the diff shows which constraint rows are missing or extra —
        with all variable names visible so you can trace back to the code.
        """
        num, combination_dir, legacy_lp = thermal_combination

        current = _generate_current_lp(combination_dir, base_parameters_dict)
        legacy_raw = SolverHelper.read_lp_ortools(str(legacy_lp))
        unit = _extract_unit_name(current)

        legacy_sigs = _constraint_signatures(legacy_raw, unit)
        current_sigs = _constraint_signatures(current, unit)

        only_legacy = legacy_sigs - current_sigs
        only_current = current_sigs - legacy_sigs

        def _fmt(counter: Counter, limit: int = 5) -> str:
            lines = []
            for sig, count in list(counter.items())[:limit]:
                vars_part = ", ".join(f"{v}×{c}" for v, c in sig[0])
                lines.append(f"  (count={count}) [{vars_part}] lb={sig[1]} ub={sig[2]}")
            if len(counter) > limit:
                lines.append(f"  ... and {len(counter) - limit} more")
            return "\n".join(lines)

        assert not only_legacy and not only_current, (
            f"[combination-{num}] Constraint mismatch:\n"
            f"Only in legacy ({sum(only_legacy.values())} rows):\n{_fmt(only_legacy)}\n"
            f"Only in current ({sum(only_current.values())} rows):\n{_fmt(only_current)}"
        )
