repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.6  # Use the latest version from https://github.com/charliermarsh/ruff-pre-commit/releases
    hooks:
    -   id: ruff-format
        args: [--config=pyproject.toml]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-toml
