site_name: Atlas
site_description: Altas documentation website
site_dir: public
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/rte-france/ATLAS
repo_name: rte-france/atlas

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.pydantic.dev/latest/objects.inv
          options:
            show_root_heading: true
            heading_level: 2
            show_signature_annotations: true
            show_if_no_docstring: true
            docstring_style: sphinx
            show_source: true
            merge_init_into_class: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            inherited_members: true
            separate_signature: true
            unwrap_annotated: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

extra_javascript:
  - custom/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.1.0/github-markdown.min.css
  - custom/custom.css

nav:
  - Home:
    - Welcome to Atlas: index.md
    - Changelog: changelog.md
    - Authors: authors.md
  - Getting Started:
    - Installation: getting_started/getting_started.md
    - Quick Start Tutorial: getting_started/quickstart.md
    - Your First Simulation: getting_started/first-simulation.md
  - User Guide:
    - With Command lines: cli.md
    - In Python Usage: modules/running-modules.md
    - Module Pattern: modules/module-pattern.md
    - Common Parameters: modules/common-parameters.md
  - Modules:
    - Overview: modules/index.md
    - Portfolio Optimisation:
      - Overview: modules/portfolio-optimisation/index.md
      - User Guide:
        - Overview: modules/portfolio-optimisation/user-guide/overview.md
        - Parameters: modules/portfolio-optimisation/user-guide/input-data.md
        - Running: modules/portfolio-optimisation/user-guide/running.md
        - Results: modules/portfolio-optimisation/user-guide/results.md
        - Examples: modules/portfolio-optimisation/user-guide/examples.md
      - Developer:
        - Architecture: modules/portfolio-optimisation/developer/architecture.md
    - Market Clearing:
      - Overview: modules/market-clearing/index.md
      - User Guide:
        - Overview: modules/market-clearing/user-guide/overview.md
        - Parameters: modules/market-clearing/user-guide/input-data.md
        - Running: modules/market-clearing/user-guide/running.md
      - Developer:
        - Architecture: modules/market-clearing/developer/architecture.md
    - Day-Ahead Orders:
        - Overview: modules/day-ahead-orders/index.md
        - User Guide:
            - Overview: modules/day-ahead-orders/user-guide/overview.md
            - Parameters: modules/day-ahead-orders/user-guide/input-data.md
            - Running: modules/day-ahead-orders/user-guide/running.md
        - Developer:
            - Architecture: modules/day-ahead-orders/developer/architecture.md
  - Examples:
    - AtlasDataset: examples/atlas_dataset.md
    - Timeseries: examples/timeseries.md
    - Matrix: examples/matrix.md
    - OptimisationModel: examples/optimisation_model.md
  - API Reference:
    - Overview: api/index.md
    - Math Objects:
      - Timeseries: api/math/timeseries.md
      - Scenario Matrix: api/math/scenario_matrix.md
      - Forecasting Matrix: api/math/forecasting_matrix.md
      - LazyTimeseries: api/math/lazy_timeseries.md
      - LazyMatrix: api/math/lazy_scenario_matrix.md
    - I/O:
      - AtlasDataset: api/io/atlas_dataset.md
    - Models:
      - Equipement: api/models/equipment.md
      - Market: api/models/market.md
    - Workflows:
      - Workflow: api/workflow/workflow.md
      - Workflow step: api/workflow/workflow_step.md
    - Optimisation:
      - Solver Interface: api/solver/interface.md
      - Other : api/solver/models.md
    - Others:
      - Enum: api/enum.md
      - Logging: api/logging.md
  - Development:
    - Contributing: contributing.md
    - Release Process: release_process.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rte-france/ATLAS
      name: "Github"
  generator: true


copyright: Copyright &copy; 2024 - Rte
