[project]
name = "atlas"
version = "0.1.0"
description = "A tool for simulating power market such as day-ahead, intraday, and reserves markets."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastparquet>=2024.11.0",
    "h5py>=3.13.0",
    "loguru>=0.7.3",
    "numpy>=2.0.1",
    "ortools>=9.12.4544",
    "pandas>=2.2.2",
    "pendulum>=3.0.0",
    "plotly>=6.0.1",
    "polars>=1.27.0",
    "pyarrow>=20.0.0",
    "pydantic>=2.11.3",
    "pydantic-extra-types>=2.10.4",
    "pytz>=2025.1",
    "pyyaml>=6.0.1",
    "typer>=0.15.2",
]


[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = false
packages.find.include = ['atlas*']

[tool.ruff]
line-length = 120
extend-exclude = ["*.ipynb"]
exclude = [
    "atlas/io/hdf_handler.py",
    "atlas/io/transform_dataset.py",
]

[tool.ruff.lint]
ignore = ["B028", "B904", "W291", "EM102", "PTH119", "D104","D212","D203","PTH118","COM812", "PTH103", "PTH100",
        "PD901", "D205", "D401", "TRY003", "D404", "EM101", "ANN204", "G004", "PTH123", "D415", "D400", "TRY301", "FBT002",
        "FBT001", "D107", "TC003", "D213", "ERA001", "TC002", "T201"]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]

[dependency-groups]
dev = [
    "ipython>=8.35.0",
    "jupyter>=1.1.1",
    "pandas-stubs>=2.2.3.250308",
    "coverage>=7.8.0",
    "mypy>=1.15.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.9.7",
    "types-pyyaml>=6.0.12.20250402",
    "pre-commit>=4.2.0",
    "plotly-stubs>=0.0.5",
]
docs = [
    "mike>=2.1.3",
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-material>=9.6.11",
    "mkdocstrings>=0.29.1",
    "mkdocstrings-python>=1.16.10",
]

[[tool.uv.index]]
url = "https://pypi.org/simple/"

[tool.mypy]
exclude = "atlas/io/transform_dataset.py"
python_version = "3.10"
strict = false
check_untyped_defs = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
warn_unused_ignores = false
warn_return_any = false
no_implicit_optional = false


[tool.coverage.run]
omit = ['atlas/io/transform_dataset.py',
        'atlas/timing.py']
