"""
Copyright (c) 2025, RTE (www.rte-france.com)

SPDX-License-Identifier: MPL-2.0
This file is part of the ATLAS project.
"""

from __future__ import annotations

from pathlib import Path
from typing import TypeVar

from pydantic import AliasChoices, Field, model_validator

from atlas.custom_errors import DataValidationError
from atlas.io_utils.parameters import ContextParameters, Parameters


class AbstractOrchestratorParameters(Parameters):
    """Parameters for the orchestrator.
    :param name: Name of the orchestrator
    :type name: str
    :param dataset_path: Path of the Dataset to use in the orchestrator
    :type dataset_path: str
    :param path_from_orchestrator: If True, resolve relative paths from orchestrator file location
    :type path_from_orchestrator: bool
    :param orchestrator_path: Absolute path to use as a root path for any related path for this orchestrator.
    :type orchestrator_path: Path
    :param output_dir: Root path, relative or absolute, for any result generated by this orchestrator
    :type output_dir: Path
    :param rollback_on_job_failure: If True, rollback CIS to previous job state when a job fails
    :type rollback_on_job_failure: bool
    :param create_job_snapshots: If True, create CIS snapshots before each job for debugging
    :type create_job_snapshots: bool
    :param export_output: Root path, relative or absolute, for any export result generated by this orchestrator
    :type export_output: Path
    :param context: Context for defaults and forced parameters values to use for all modules.
    :type context: ContextParameters
    """

    name: str | None = None
    dataset_path: Path
    path_from_orchestrator: bool = Field(
        default=True,
        validation_alias=AliasChoices("path_from_orchestrator", "path_from_workflow", "path_from_action_plan"),
    )
    orchestrator_path: Path = Field(
        default=Path(),
        validation_alias=AliasChoices("orchestrator_path", "workflow_path", "action_plan_path"),
    )
    output_dir: Path = Path()
    rollback_on_job_failure: bool = True
    create_job_snapshots: bool = False
    export_output: bool = True
    context: ContextParameters = ContextParameters()

    @model_validator(mode="after")
    def validate_use_of_relative_path(self) -> AbstractOrchestratorParameters:
        if not self.path_from_orchestrator:
            return self

        if not self.orchestrator_path.absolute():
            raise DataValidationError(
                f"Path {self.orchestrator_path} is not an absolute path."
                f'This path used for orchestrator {self.name} parameter "orchestrator_path" and has to be an absolute path.'
            )
        elif not self.orchestrator_path.exists():
            raise DataValidationError(
                f"Path {self.orchestrator_path} doesn't exist."
                f'This path used for orchestrator {self.name} parameter "orchestrator_path" and has to be an existing path.'
            )
        return self

    @property
    def base_path(self) -> Path:
        """Returns the orchestrator base path if path_from_orchestrator is True, otherwise empty Path.

        This allows paths in parameters to be either:
        - Relative (resolved from orchestrator file location if path_from_orchestrator=True)
        - Absolute (used as-is regardless of path_from_orchestrator)

        :return: Base path for resolving relative paths
        :rtype: Path
        """
        return self.orchestrator_path if self.path_from_orchestrator else Path()

    def resolve_path(self, path: Path) -> Path:
        """Resolve a path based on path_from_orchestrator setting.

        :param path: Path to resolve (can be relative or absolute)
        :type path: Path
        :return: Resolved path (absolute paths returned as-is, relative paths resolved from base_path)
        :rtype: Path
        """
        if path.is_absolute():
            return path
        return self.base_path / path


PO = TypeVar("PO", bound=AbstractOrchestratorParameters)
