name: Build Documentation

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  doc-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --group docs --no-dev

      - name: Build documentation website
        run: uv run zensical build --config-file zensical.toml
