name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Test with pytest and coverage (without integration tests)
        if: github.event_name == 'push'
        run: uv run pytest -v --cov=atlas --cov-report=xml --disable-warnings -m "not integration"

      - name: Test with pytest and coverage (with integration tests)
        if: github.event_name == 'pull_request'
        run: uv run pytest -v --cov=atlas --cov-report=xml --disable-warnings -m ""
